chapter_1 = [
"Here begins the tale, and tells of a man who was named Sigi, and called of men the son of Odin; another man withal is told of in the tale, hight Skadi, a great man and mighty of his hands; yet was Sigi the mightier and the higher of kin, according to the speech of men of that time. Now Skadi had a thrall with whom the story must deal somewhat, Bredi by name, who was called after that work which he had to do; in prowess and might of hand he was equal to men who were held more worthy, yea, and better than some thereof.",
"Now it is to be told that, on a time, Sigi fared to the hunting of the deer, and the thrall with him; and they hunted deer day-long till the evening; and when they gathered together their prey in the evening, lo, greater and more by far was that which Bredi had slain than Sigi's prey; and this thing he much misliked, and he said that great wonder it was that a very thrall should out-do him in the hunting of deer:",
"so he fell on him and slew him, and buried the body of him thereafter in a snow-drift.",
"Then he went home at evening tide and says that Bredi had ridden away from him into the wild-wood. 'Soon was he out of my sight,' he says, 'and naught more I wot of him.'",
"Skadi misdoubted the tale of Sigi, and deemed that this was a guile of his, and that he would have slain Bredi. So he sent men to seek for him, and to such an end came their seeking, that they found him in a certain snow-drift; then said Skadi, that men should call that snow-drift Bredi's Drift from henceforth; and thereafter have folk followed, so that in such wise they call every drift that is right great.",
"Thus it is well seen that Sigi has slain the thrall and murdered him; so he is given forth to be a wolf in holy places, and may no more abide in the land with his father;",


]

chapter_conclusion = ["Therewith Woden bare him fellowship from the land, so long a way, that right long it was, and made no stay till he brought him to certain war-ships. So Sigi falls to lying out a-warring with the strength that his father gave him or ever they parted; and happy was he in his warring, and ever prevailed, till he brought it about that he won by his wars land and lordship at the last; and thereupon he took to him a noble wife, and became a great and mighty king, and ruled over the land of the Huns, and was the greatest of warriors. He had a son by his wife, who was called Rerir, who grew up in his father's house, and soon became great of growth, and shapely."	
]